# Generated by Django 6.1 on 2026-08-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_webpushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
