# Generated by Django 6.1 on 2026-08-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share_stats_with_groups',
            field=models.BooleanField(default=False),
        ),
    ]
